version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mysql
      - DB_NAME=livros
      - DB_PORT=3306

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: livros
    volumes:
      - db-data:/var/lib/mysql
      - ./api-livros/src/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  db-data:
